# Generated by Django 3.0.3 on 2020-02-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_position', models.CharField(max_length=100)),
                ('player_photo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_team', models.CharField(default='Enter team', max_length=100)),
                ('player_point', models.CharField(default='Enter points', max_length=100)),
                ('player_rebound', models.CharField(default='Enter rebounds', max_length=100)),
                ('player_assist', models.CharField(default='Enter assists', max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='nba_app.Player')),
            ],
        ),
    ]
